<a href="https://colab.research.google.com/github/MelihKlc/Deep-Learning/blob/main/Broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
A = np.array(
    [
      [56.0 , 0.0 , 4.4 , 68.0] ,
      [1.2 , 104.0 , 52.0 , 8.0] ,
      [1.8 , 135.0 , 99.0 , 0.9]
    ]
)
A

array([[ 56. ,   0. ,   4.4,  68. ],
       [  1.2, 104. ,  52. ,   8. ],
       [  1.8, 135. ,  99. ,   0.9]])

In [ ]:
cal = A.sum(axis = 0)
cal

array([ 59. , 239. , 155.4,  76.9])

In [ ]:
percentage = 100*A/cal.reshape(1 , 4)
percentage

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

# For example we have matrix with shape ( 2 , 3 ) and another matrix with shape ( 1 , 3 ). When we want to add these two , pyhton automatically expand the second matrix's shape with ( 2 , 3 )

## In theory , you have ( m , n ) matrix and if the other matrix has ( 1 , n ) ,  it will broadcast ( m , n ). Same principle for ( m , 1 ).