<a href="https://colab.research.google.com/github/MelihKlc/Deep-Learning/blob/main/Bug_Free_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.random.randn(5)

In [3]:
a

array([-0.52813294, -1.89158714, -0.6993573 , -2.18359751, -1.2525455 ])

In [4]:
a.shape   # It is called rank 1 array. Neither row nor column vector

(5,)

In [5]:
a.T

array([-0.52813294, -1.89158714, -0.6993573 , -2.18359751, -1.2525455 ])

In [6]:
np.dot(a , a.T)  # Instead of this , we want to use the shape of (5,1) instead of rank vector

10.683095242401533

In [7]:
a = np.random.rand( 5 , 1)
a

array([[0.27391255],
       [0.76013696],
       [0.3550639 ],
       [0.16332082],
       [0.07323978]])

In [8]:
a.shape

(5, 1)

In [9]:
a.T

array([[0.27391255, 0.76013696, 0.3550639 , 0.16332082, 0.07323978]])

In [10]:
np.dot( a , a.T )

array([[0.07502808, 0.20821105, 0.09725646, 0.04473562, 0.02006129],
       [0.20821105, 0.5778082 , 0.2698972 , 0.12414619, 0.05567226],
       [0.09725646, 0.2698972 , 0.12607037, 0.05798933, 0.0260048 ],
       [0.04473562, 0.12414619, 0.05798933, 0.02667369, 0.01196158],
       [0.02006129, 0.05567226, 0.0260048 , 0.01196158, 0.00536407]])

# Dont use rank 1 array when you implement a neural network. Everytime , reshape your arrays with this form ( 5 , 1 ) or ( 1 , 5 ) (it is just an example) when you use column or row vector.

In [11]:
# For make sure your vectors' shape
assert( a.shape == ( 5 , 1 ) )

# a.reshape( ( 5 , 1) )   or a.reshape( ( 1 , 5 ) )