<a href="https://colab.research.google.com/github/MelihKlc/Deep-Learning/blob/main/Fundamentals_of_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

  # Introduction to Tensors

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [ ]:
  #Creating tensors with tf.constant()
  scalar = tf.constant(7)  #ctrl shift space özellikleri görmek için
  scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#check the number of dimensions of a tensor (ndim stands for number of dimension)
scalar.ndim

0

In [ ]:
#Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#check the number of dimension
vector.ndim

1

In [ ]:
#Create a matrix (Matrix have more than 1 dimension)
matrix = tf.constant([[10,7],[7,10]])  #int32 32 bit precision  bunu float16 yaparsak mesela memoryde daha az yer kaplıyor
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#Create another matrix
another_matrix = tf.constant([[10.,7.] ,
                                                [ 3.,2.] ,
                                                [8.,9.]] , dtype = tf.float16)  #specify the data type with dtype parameter.  3 row 2 column
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
#Lets create a tensor
tensor = tf.constant([[[1,2,3] ,
                      [4,5,6 ]] ,
                     [[7,8,9] ,
                      [10,11,12]] ,
                      [[13,14,15] ,
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
#What we have created?
#Scalar : a single number
#Vector : a number of with direction (e.g wind speed and direction)
#Matrix : a 2-dimensional array of numbers
#Tensor : a n-dimensional array of numbers (when n can be any number , a 0-dimensional tensor is scalar , a 1-dimensional tensor is vector , a 2-dimensional tensor is matrix )

### Creating tensors with tf.variable

In [ ]:
#Create the same tensor with tf.Variable( ) as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor , unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#Lets try the change one of the elements of the changeable tensor
changeable_tensor[0].assign(7)  # 0. indexi 7 ile değiştirmek için
changeable_tensor  #.variable değiştirilebilen tensor oluşturuyor .constant içinde değişiklik yapamıyoruz.

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

## Creating random tensors

In [ ]:
#Random tensors are tensors of some arbitrary size which contain random numbers
#Create 2 random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42)  #set seed for reproductibility. Burda 42 verdiğimiz machine learningteki random_size ile aynı mantık
random_1 = random_1.normal(shape = (3,2))  #3 row 2 columndan oluşan ve normal distributionla yapılan bir tensor oluşturduk.
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3,2))

random_1 , random_2 , random_1 == random_2   #== ile equality bakıyoruz

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

## Shuffle the order of elements in tensor

In [ ]:
#Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesnt effect learning) bizim datamızda mesela 1000 spagetti 500 ramen varsa ve bu 1000 spagetti en baştaysa shuffle yani karıştırmak daha iyi çünkü karıştırmazsak neural network ilk başta sadece spagettileri öğrenecek.
not_shuffled = tf.constant([[10,7] ,
                            [3,4],
                           [5,2]])
tf.random.shuffle(not_shuffled)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 5,  2],
       [ 3,  4]], dtype=int32)>

In [ ]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 5,  2]], dtype=int32)>

In [ ]:
randomt_1 = tf.constant([[3,5] ,
                         [6,2] ,
                         [7,3] ,
                         [8,12] ,
                         [ 9, 15] ])
tf.random.set_seed(32) #global level seed
tf.random.shuffle(randomt_1 , seed = 15000) #operational level seed
#eğer hem global hem operational belirlersek bizim tensorumuz önce shuffle oluyor sonrasında o shuffle olmuş hali hiç bozulmuyor. ama sadece operational kullansaydık her seferinde farklı shuffle olacaktı





<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[ 7,  3],
       [ 9, 15],
       [ 6,  2],
       [ 8, 12],
       [ 3,  5]], dtype=int32)>

## Other ways to make tensors

In [ ]:
#Create a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
#Create a tensor of all zeros
tf.zeros(shape = (3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

## The numpy arrays into tensors
### The main difference between numpy arrays and tensorflow tensors is that tensors can be run on  a GPU(much faster for numerica computing)

In [ ]:
#numpy array into tensors
#X = tf.constant(some_matrix)  capital letter for matrixes
#y = tf.constant(vectors)   non-capital letter for vectors
import numpy as np
numpy_A = np.arange(1 , 25 , dtype = np.int32) #create a numpy array between 1 and 25
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A)  #numpy arrayi direkt bu şekilde tensora çevirebiliyoruz
B = tf.constant(numpy_A , shape = (2,3,4))  #burada resahep yaparak 3 dimensiona çevirdik ama dikkat etmemiz gereken şey 2*3*4 = 24 olduğu için oldu 24 elemanı tam 3 dimensiona uyarlayabildiğimiz için yani.
C = tf.constant(numpy_A , shape = (3,8))
A , B , C

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>)

## Getting information from tensors
* Shape
* Rank
* Axis or dimension
* Size

In [ ]:
#Create a rank 4 tensor (4 dimension)
rank_4_tensor = tf.zeros(shape = [2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape , rank_4_tensor.ndim , tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
2*3*4*5

120

In [ ]:
#Get various attribute of our tensor
print("Datatype of every element: " , rank_4_tensor.dtype)
print("Elements along the 0 axis: " , rank_4_tensor.shape[0])
print("Elements along the last axis: " , rank_4_tensor.shape[-1])

Datatype of every element:  <dtype: 'float32'>
Elements along the 0 axis:  2
Elements along the last axis:  5


## Indexing tensors
### Tensors can be indexed just like python lists

In [ ]:
#Get the first two elements of each dimension
rank_4_tensor[ : 2 , : 2 , : 2 , : 2 ]


<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
#Get the first element from each dimension from each index except the final one
rank_4_tensor[ : 1 , : 1 , : 1 , :]   #dahil etmek istemediğimiz şeyi sadece : koyarak elde ediyoruz.

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
#Create a rank 2 tensor (2-dimension)
rank_2_tensor = tf.constant([[10,7],[3,4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
#Get the last item of each our rank 2 tensor
rank_2_tensor[  :  ,  -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
#Add an extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[ ... , tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
#Alternative of tf.newaxis
tf.expand_dims(rank_2_tensor , axis = -1)  #expand_dims de dimension ekliyor. axis = -1 demek de ekleyeceği dimensionu son columna eklemek için yapılıyor. -1 means expand the final axis

## Manipulating Tensors

### Basic operations ( ' + '  , ' - ' , ' * ' , ' / ' )

In [ ]:
#You can add values to a tensor using the addition operator.
tensor = tf.constant([[ 10 , 7 ] , [ 3 , 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
#Original tensor is unchanged. Sadece 10 eklediğimiz kısımda tensor ın içeriği değişiyor. Eğer tensoru değiştirmek istiyorsak uptade etmemiz gerek
#Subtraction and multiplication da toplamayla aynı çalışıyor. Subtraction da herhangi bir sorun olmuyor yani tensorlar negative valueları da storelayabiliyor.

In [ ]:
#We can use the tensorflow built-in function too
tf.multiply( tensor , 10 )  #tensor ismini yazıyoruz ilk parametreye sonra kaçla çarpmak istediğimizi. Diretk multiplication operatörüne göre tensorflow kodunu kullanmak daha hızlı execute sağlıyor. Fakat yukarda da olduğu gibi original tensor yine değişmiyor.

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

# Matrix multiplication
## In machine learning , matrix multiplication is one of the most common tensor operation

In [ ]:
#If we say tensor * tensor directly , this is an elementwise multiplication, so its just multiply one by one all elements.
tf.matmul(tensor , tensor)  #Bu direkt matrix multiplication with dot product

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
#Matrix multiplication with python operator @
tensor @ tensor  #bu da dot product oluyor.

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor_1 = tf.constant([[ 1 , 2 , 5] , [ 7 , 2 , 1] , [ 3 , 3 , 3 ]])
tensor_2 = tf.constant([[ 3 , 5] , [ 6 , 7] , [ 1 , 8 ]])
tf.matmul( tensor_1 , tensor_2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
#Matris çarpımın kuralları:
#1) Matrislerin inner sayıları eşleşmesi gerekiyor yani ilk matris 4x3 se ikinci matrisin row sayısı 3 olmalı mesela 3x5. Bu durumda çarpım sonucu oluşan matrisimiz 4x5 bir matris oluyor
#Eğer çarpımı shape den dolayı yapamıyorsak reshape veya transpose kullanabiliriz fakat bunların sonucu farklı çıkacak. Genel olarak eğer ki çarptığın matrislerin shape leri uymuyorsa matrislerden birine  transpose yapacağız.

In [ ]:
#Create a tensor with default datatype (float32)
B = tf.constant([[ 10.1 ,7.2 ] , [ 3 , 4 ]])
B , B.dtype

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[10.1,  7.2],
        [ 3. ,  4. ]], dtype=float32)>,
 tf.float32)

In [ ]:
#Change from float32 to float16 (reduced precision)
B = tf.cast(B , dtype = tf.float16)
B , B.dtype

(<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
 array([[10.1,  7.2],
        [ 3. ,  4. ]], dtype=float16)>,
 tf.float16)

# Aggregating Tensors
## Aggregating Tensors = condensing them from multiple values down to a smaller amount of values

In [ ]:
#Get the absolute values
D = tf.constant([ -7 , -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
#Get the absolute values
tf.abs(D)  #absolute value alıyor bütün negative değerler için

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

# Lets go through the following forms of aggregation
* get the minimum
* get the maximum
* get the mean of tensor
* get the sum of a tensor

In [ ]:
#Create a random tensor with values between 0 to 100 with size of 50
E = tf.constant(np.random.randint( 0 , 100 , size = 50))  #random.randint numpy fonksiyonuyla 0 la 100 arasında random 50 sayı seçtik
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([46, 25, 67, 62, 41, 15, 48, 19, 81, 73, 34, 55, 33, 50, 49, 32, 99,
       34, 70, 97, 12, 38, 32, 59, 85, 16, 84, 39, 51, 54, 95, 90,  0, 40,
       71, 10, 33, 24, 58, 58, 60, 74, 34, 17, 72, 81, 94, 77, 14, 94])>

In [ ]:
tf.size(E)

<tf.Tensor: shape=(), dtype=int32, numpy=50>

In [ ]:
#Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
#Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
#Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=51>

In [ ]:
#Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2596>

In [ ]:
#Find the variance
E = tf.cast(E , dtype = tf.float32)  #Float32 olmadan hesaplayamıyoruz variance ve std için real veya complex
tf.math.reduce_variance(E)

<tf.Tensor: shape=(), dtype=float32, numpy=704.03357>

In [ ]:
#Find the standart deviation
tf.math.reduce_std(E)


<tf.Tensor: shape=(), dtype=float32, numpy=26.53363>

# Find the positional maximum and minimum

In [ ]:
#Create a new tensor for finding positional maximum and minimum. Burda bizim neural networkumuzden çıkan representation outputumuza bakıcaz. şimdi mesela ilk row ramen i temsil ediyor. Burda bir olasılık diğerlerinden çok daha fazla oluyor mesela sıfırıncı index 0.965 çıkmış yani [0,0] bize ramen olma olasılığını veriyor
tf.random.set_seed(42)
F = tf.random.uniform(shape = [50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
#Find the positional max
tf.argmax(F)  #42. element en büyük yani argmaxle kaçıncı elementin en büyük oldugunu buluyoruz.

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
#Index of our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
#Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
#Find the positional min
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
#Find the minimum value with positional min
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

# Squeezing a tensor (removing all single dimensions)

In [ ]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape = [50]) , shape = (1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed , G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

# One hot encoding

In [ ]:
#Create a list of indices.
some_list = [0 , 1 , 2 , 3]  #could be red, blue, green , gray
tf.one_hot(some_list , depth = len(some_list))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

# Squaring , root , square root

In [ ]:
#Create a new tensor
H = tf.range(1 , 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
#Square it
tf.square(H)


<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
#Find the square root
H = tf.cast(H , dtype = tf.float32)
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
#Find the log
H = tf.cast(H , dtype = tf.float32)
tf.math.log(H)


<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# Tensors and Numpy
## tensorflow interacts beautifully with numpy arrays

In [ ]:
#Create a tensor directly from a numpy array
J = tf.constant(np.array( [ 3. , 7. , 10.  ]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
#Convert our tensor back to a numpy array
np.array(J) , type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
#Convert tensor J to a numpy array
J.numpy() , type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
#The default types of each are slightly different
nump_J = tf.constant(np.array([3. , 7. , 10.]))
tensor_J = tf.constant([3. , 7. , 10.])
nump_J.dtype  , tensor_J.dtype

(tf.float64, tf.float32)

# Finding access to GPUs

In [ ]:
import tensorflow as tf
tf.config.list_physical_devices()  #çalışma zamanından çalışma zamanının türünü değiştir yapıp gpu veya tpu seçiyoruz

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Sat Jul 22 16:32:24 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   63C    P8    11W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

# If you have access to a CUDA-enabled GPU, Tensorflow will automatically use it whenever possible