<a href="https://colab.research.google.com/github/MelihKlc/Deep-Learning/blob/main/np_sum_np_random_randn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.random.randn(4 , 3)
b = np.sum(a , axis = 1 , keepdims = True)

In [ ]:
b

array([[ 5.11326189],
       [ 2.16631548],
       [ 0.90516176],
       [-1.27509171]])

In [ ]:
a

array([[ 2.16301372,  0.54496649,  2.40528169],
       [ 0.96826927, -0.87854153,  2.07658774],
       [ 0.96538449,  0.53528457, -0.59550731],
       [-1.21891578, -0.52280101,  0.46662507]])

In [ ]:
x = np.random.randn( 4 , 5 )
y = np.sum(x , axis = 1)

In [ ]:
y.shape

(4,)

In [ ]:
x

array([[ 0.31225886,  0.65834327,  2.08341326,  0.74462801, -0.4209443 ],
       [-0.65066576,  0.91875398,  0.42463797, -0.6472121 , -0.76157646],
       [-1.05360054,  0.45322018,  0.37162341,  1.81846752,  0.10192781],
       [-0.18510436, -0.9831291 , -2.32791358,  1.12144488, -0.55777683]])