<a href="https://colab.research.google.com/github/MelihKlc/Deep-Learning/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Why numpy?
1. If we use python lists , it would actually be a lot slower than numpy lists because numpy is coded with C Programming.
2. Machines learns by performing multiple operations and by storing this information in an array like numpy. Numpy is a great way for us to represent that data from what humans can understand to what computers can understand

# What is numpy?
Numpy is going to form the foundation of turning your data into a series of numbers.

### Arrays = list of numbers

## What are we going to cover?
1. Most useful functions.
2. Numpy datatypes and attributes.(ndarray)
3. Creating arrays.
4. Viewing arrays & matrices (matrices = you can imagine as a combination of different arrays.)
5. Manipulating & comparing arrays.
6. Sorting arrays.
7. Use cases

In [1]:
import numpy as np

## Datatypes & Attributes
Numpy's main datatype is ndarray

In [3]:
# As i said , we create a list of numbers , so we should create a list into the numpy array.
a1 = np.array(
    [
        1,2,3
    ]
)
a1



array([1, 2, 3])

for a1
* Names : array , vector
* 1-dimensional
* Shape = (1,3)

In [4]:
a2 = np.array(
    [ [ 1 , 2.0 , 3.3 ] ,
     [ 4 , 5 , 6.5 ] ]
)

a3 = np.array(
     [ [ [ 1 , 2 , 3 ] ,
     [ 4 , 5 , 6 ] ,
      [ 7 , 8 , 9 ] ] ,
       [ [ 10 , 11 , 12 ] ,
        [ 13 , 14 , 15 ] ,
         [ 16 , 17 , 18] ] ]
)

for a2
* Names : array , matrix
* More than 1-dimension
* Shape = (2,3)

for a3
* Names : array , matrix
* More than 1-dimension
* Shape = ( 2 , 3 , 3 )

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim , a2.ndim , a3.ndim  # Dimension of arrays

(1, 2, 3)

In [11]:
a1.dtype , a2.dtype  , a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [12]:
a1.size , a2.size , a3.size  # Number of elements

(3, 6, 18)

In [13]:
type(a1) , type(a2) , type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
# Create a DataFrame from a numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

Machine Learning finding patterns in numpy arrays

## Creating arrays

In [16]:
sample_array = np.array([
    1,2,3
])
sample_array

array([1, 2, 3])

In [17]:
sample_array.dtype

dtype('int64')

In [18]:
ones = np.ones(shape = (2 , 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ones.dtype

dtype('float64')

In [20]:
type(ones)

numpy.ndarray

In [21]:
zeros = np.zeros(shape = (2 , 3))
zeros


array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
range_array = np.arange( 0 , 10 ,  2  )  # start , stop , step
range_array

array([0, 2, 4, 6, 8])

In [24]:
random_array = np.random.randint( 0 , 10 , size = ( 3 , 5 ) )  # lowest , highest , shape of array
random_array

array([[5, 4, 1, 2, 5],
       [6, 4, 7, 2, 3],
       [6, 2, 0, 4, 0]])

In [25]:
random_array.size

15

In [26]:
random_array.shape

(3, 5)

In [28]:
random_array_2 = np.random.random( ( 5 , 3 ) )  # Return random floats in the interval [ 0 , 1)
random_array_2

array([[0.36589307, 0.67541987, 0.65651918],
       [0.25692485, 0.09236447, 0.08728403],
       [0.08117165, 0.71522413, 0.11294494],
       [0.50053777, 0.85952051, 0.98232878],
       [0.05500885, 0.70340236, 0.26169197]])

In [29]:
random_array_2.size

15

In [30]:
random_array_2.shape

(5, 3)

In [31]:
random_array_3 = np.random.rand( 5 , 3 )
random_array_3

array([[0.49348729, 0.76956816, 0.27285484],
       [0.84427348, 0.63014589, 0.94432409],
       [0.25014955, 0.91477329, 0.23149884],
       [0.59910006, 0.49790603, 0.38836998],
       [0.82545664, 0.90113084, 0.46401031]])

In [41]:
# Pseudo random numbers
np.random.seed(9999)
random_array_4 = np.random.randint( 10 , size = ( 5 , 3 ) )
random_array_4

array([[6, 1, 6],
       [5, 5, 9],
       [6, 8, 0],
       [8, 1, 5],
       [3, 1, 0]])

In [39]:
np.random.seed(42)  # Sadece bu satır için seed oluyor bu. Global seed degil.
random_array_5 = np.random.random( ( 5 , 3 ) )
random_array_5

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497]])

## Viewing arrays and matrices

In [42]:
np.unique(random_array_4)

array([0, 1, 3, 5, 6, 8, 9])

In [43]:
a1[0]

1

In [46]:
a2.shape

(2, 3)

In [44]:
a2[0]

array([1. , 2. , 3.3])

In [47]:
a3.shape

(2, 3, 3)

In [45]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [49]:
a3[ : 2 , : 2 , : 2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [50]:
a4 = np.random.randint( 10 , size = ( 2 , 3 , 4 , 5 ) )  # Size da en sağdaki innermost oluyor.
a4

array([[[[6, 4, 4, 6, 8],
         [4, 7, 1, 9, 3],
         [9, 3, 3, 9, 1],
         [8, 9, 0, 3, 5]],

        [[0, 5, 9, 9, 5],
         [0, 3, 6, 0, 9],
         [8, 9, 6, 4, 6],
         [9, 8, 6, 3, 2]],

        [[9, 2, 1, 5, 6],
         [4, 0, 2, 4, 7],
         [6, 8, 1, 0, 6],
         [2, 3, 3, 9, 3]]],


       [[[2, 3, 0, 7, 6],
         [7, 9, 0, 9, 8],
         [4, 1, 1, 2, 1],
         [1, 6, 8, 9, 7]],

        [[9, 3, 6, 6, 9],
         [1, 8, 8, 7, 2],
         [2, 2, 3, 7, 1],
         [8, 3, 4, 9, 4]],

        [[8, 9, 9, 2, 0],
         [6, 4, 6, 7, 9],
         [4, 0, 7, 8, 5],
         [4, 6, 5, 0, 0]]]])

In [51]:
a4.shape , a4.ndim

((2, 3, 4, 5), 4)

In [56]:
a4[ 1 , 1 ,  0 , : 4 ]

array([9, 3, 6, 6])

In [57]:
# Get the first 4 numbers of the innermost arrays
a4[ : , : , : , : 4 ]

array([[[[6, 4, 4, 6],
         [4, 7, 1, 9],
         [9, 3, 3, 9],
         [8, 9, 0, 3]],

        [[0, 5, 9, 9],
         [0, 3, 6, 0],
         [8, 9, 6, 4],
         [9, 8, 6, 3]],

        [[9, 2, 1, 5],
         [4, 0, 2, 4],
         [6, 8, 1, 0],
         [2, 3, 3, 9]]],


       [[[2, 3, 0, 7],
         [7, 9, 0, 9],
         [4, 1, 1, 2],
         [1, 6, 8, 9]],

        [[9, 3, 6, 6],
         [1, 8, 8, 7],
         [2, 2, 3, 7],
         [8, 3, 4, 9]],

        [[8, 9, 9, 2],
         [6, 4, 6, 7],
         [4, 0, 7, 8],
         [4, 6, 5, 0]]]])

## Manipulating and comparing arrays

### Arithmetic

In [58]:
a1

array([1, 2, 3])

In [60]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [61]:
a1 + ones

array([2., 3., 4.])

In [62]:
a1 - ones

array([0., 1., 2.])

In [63]:
a1 * ones

array([1., 2., 3.])

In [64]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [66]:
a1.shape , a2.shape

((3,), (2, 3))

In [65]:
a1 * a2  # Smaller array is brodcast across the larger array , so they have compatible shapes.

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [68]:
a2 // a1   # Floor division removes the decimals ( rounds down )

array([[1., 1., 1.],
       [4., 2., 2.]])

In [69]:
a2 ** 2 # square

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [70]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [71]:
np.exp(a1)  # Exponential

array([ 2.71828183,  7.3890561 , 20.08553692])

In [72]:
np.log(a1) # Logarithm

array([0.        , 0.69314718, 1.09861229])

## Aggregation

Performing the same operation on a number of things

In [73]:
list = [ 1 , 2 , 3 ]
type(list)

list

In [74]:
sum(list)

6

Use python methods on python datatypes , use numpy methods on numpy arrays

In [75]:
# Create a massive numpy array
massive_array = np.random.random(100000)
massive_array[ : 10]

array([0.70094371, 0.3916583 , 0.52507578, 0.12748888, 0.9145109 ,
       0.88871383, 0.59378791, 0.60909572, 0.36100727, 0.63634928])

In [76]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [77]:
np.mean(a2)

3.6333333333333333

In [78]:
np.max(a2)

6.5

In [79]:
np.min(a2)

1.0

In [80]:
# Standart deviation = A measure of how spread out a group of numbers is from the mean
np.std(a2)

1.8226964152656422

In [81]:
np.var(a2) # Variance = Measure of the average degree to which each number is different to the mean
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers

3.3222222222222224