<a href="https://colab.research.google.com/github/MelihKlc/Deep-Learning/blob/main/Project_1_Heart_Disease.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# An end-to-end Scikit-Learn worfklow
1. Getting the data ready
2. Choosing the right maching learning estimator/aglorithm/model for your problem
3. Fitting your chosen machine learning model to data and using it to make a prediction
4. Evaluting a machine learning model
5. Improving predictions through experimentation (hyperparameter tuning)
6. Saving and loading a pretrained model
7. Putting it all together in a pipeline

## 1- Getting the data ready

In [1]:
!wget https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/heart-disease.csv

--2023-09-13 14:09:56--  https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/heart-disease.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11328 (11K) [text/plain]
Saving to: ‘heart-disease.csv.2’

heart-disease.csv.2 100%[===================>]  11.06K  --.-KB/s    in 0s      

2023-09-13 14:09:57 (77.5 MB/s) - ‘heart-disease.csv.2’ saved [11328/11328]



In [2]:
import pandas as pd
heart_diseas = pd.read_csv("/content/heart-disease.csv")
heart_diseas


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [3]:
# Create X (features matrix)
X = heart_diseas.drop("target" , axis = 1)
# Create y (labels)
y = heart_diseas["target"]

In [4]:
# Create test and training set
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(
    X , y , test_size = 0.2 , random_state= 42
)
len(X_train) , len(X_test) , len(y_train) , len(y_test)

(242, 61, 242, 61)

In [5]:
# Testing our output is binary or not
y.nunique() # We have zero and 1 for output

2

## Our problem is classification problem

Lets create a neural network (baseline)

In [6]:
import tensorflow as tf
baseline = tf.keras.Sequential(
    [
        tf.keras.layers.Dense(1)
    ]
)
baseline.compile(
    loss = tf.keras.losses.BinaryCrossentropy() ,
    optimizer = tf.keras.optimizers.Adam() ,
    metrics = ["accuracy"]
)
hist_0 = baseline.fit(
    X_train ,
    y_train ,
    epochs = 10 ,
    validation_data = ( X_test  , y_test)
)


Epoch 1/10
8/8 [==============================] - 2s 94ms/step - loss: 6.8685 - accuracy: 0.5496 - val_loss: 7.2496 - val_accuracy: 0.5246
Epoch 2/10
8/8 [==============================] - 0s 21ms/step - loss: 6.8685 - accuracy: 0.5496 - val_loss: 7.2496 - val_accuracy: 0.5246
Epoch 3/10
8/8 [==============================] - 0s 13ms/step - loss: 6.8685 - accuracy: 0.5496 - val_loss: 7.2496 - val_accuracy: 0.5246
Epoch 4/10
8/8 [==============================] - 0s 19ms/step - loss: 6.8685 - accuracy: 0.5496 - val_loss: 7.2496 - val_accuracy: 0.5246
Epoch 5/10
8/8 [==============================] - 0s 19ms/step - loss: 6.8685 - accuracy: 0.5496 - val_loss: 7.2496 - val_accuracy: 0.5246
Epoch 6/10
8/8 [==============================] - 0s 13ms/step - loss: 6.8685 - accuracy: 0.5496 - val_loss: 7.2496 - val_accuracy: 0.5246
Epoch 7/10
8/8 [==============================] - 0s 13ms/step - loss: 6.8685 - accuracy: 0.5496 - val_loss: 7.2496 - val_accuracy: 0.5246
Epoch 8/10
8/8 [===========

In [7]:
# Make prediction with our baseline
baseline_pred = baseline.predict(
    X_test
)
baseline_pred

2/2 [==============================] - 0s 7ms/step


array([[53.939777],
       [54.593517],
       [39.98475 ],
       [50.431946],
       [40.91385 ],
       [41.585743],
       [42.977512],
       [64.11973 ],
       [44.092106],
       [41.249985],
       [43.538006],
       [55.137585],
       [41.410675],
       [32.833366],
       [29.707735],
       [41.27153 ],
       [30.597822],
       [38.853657],
       [49.13669 ],
       [42.237232],
       [52.168583],
       [47.13964 ],
       [46.914406],
       [54.450268],
       [36.475487],
       [43.545593],
       [55.045277],
       [43.072838],
       [57.75271 ],
       [36.04631 ],
       [46.739613],
       [44.374832],
       [44.446533],
       [30.817848],
       [48.338593],
       [43.42311 ],
       [38.098774],
       [38.683197],
       [36.80933 ],
       [35.638084],
       [42.18351 ],
       [42.997475],
       [42.3552  ],
       [36.709675],
       [36.87107 ],
       [42.901173],
       [39.54705 ],
       [36.947346],
       [53.271156],
       [53.18799 ],


In [8]:
# Improving our model because now it seem like sh1t. I will add activations and output layer
model_1 = tf.keras.Sequential(
    [
        tf.keras.layers.Dense(10 , activation = "relu") ,
        tf.keras.layers.Dense(1 , activation = "sigmoid")
    ]
)
model_1.compile(
    loss = tf.keras.losses.BinaryCrossentropy() ,
    optimizer = tf.keras.optimizers.Adam() ,
    metrics = ["accuracy"]
)
hist_1 = model_1.fit(
    X_train ,
    y_train ,
    epochs = 10 ,
    validation_data = ( X_test  , y_test)
)


Epoch 1/10
8/8 [==============================] - 2s 86ms/step - loss: 15.2627 - accuracy: 0.4463 - val_loss: 11.8805 - val_accuracy: 0.4754
Epoch 2/10
8/8 [==============================] - 0s 13ms/step - loss: 11.3122 - accuracy: 0.4421 - val_loss: 8.3831 - val_accuracy: 0.4590
Epoch 3/10
8/8 [==============================] - 0s 11ms/step - loss: 7.7386 - accuracy: 0.4380 - val_loss: 5.1804 - val_accuracy: 0.4262
Epoch 4/10
8/8 [==============================] - 0s 25ms/step - loss: 4.4961 - accuracy: 0.4008 - val_loss: 3.2735 - val_accuracy: 0.2951
Epoch 5/10
8/8 [==============================] - 0s 13ms/step - loss: 2.5540 - accuracy: 0.4174 - val_loss: 3.2829 - val_accuracy: 0.3443
Epoch 6/10
8/8 [==============================] - 0s 11ms/step - loss: 2.3117 - accuracy: 0.4256 - val_loss: 3.4902 - val_accuracy: 0.3934
Epoch 7/10
8/8 [==============================] - 0s 14ms/step - loss: 2.2453 - accuracy: 0.4545 - val_loss: 3.1620 - val_accuracy: 0.3607
Epoch 8/10
8/8 [========

In [9]:
model_1_preds = model_1.predict(X_test)
model_1_preds

2/2 [==============================] - 0s 5ms/step


array([[0.9992189 ],
       [0.9968595 ],
       [0.98710126],
       [0.14061326],
       [0.11395069],
       [0.8898743 ],
       [0.8838101 ],
       [0.9999955 ],
       [0.81842446],
       [0.5093171 ],
       [0.7942554 ],
       [0.99934524],
       [0.10707523],
       [0.7247287 ],
       [0.00294296],
       [0.5950936 ],
       [0.01860012],
       [0.7863968 ],
       [0.9958054 ],
       [0.9561144 ],
       [0.9958425 ],
       [0.9415054 ],
       [0.6473123 ],
       [0.91550326],
       [0.53251314],
       [0.847843  ],
       [0.9996004 ],
       [0.18151598],
       [0.9998636 ],
       [0.04856519],
       [0.8559771 ],
       [0.75331527],
       [0.57085687],
       [0.02584048],
       [0.9927199 ],
       [0.31414884],
       [0.17531694],
       [0.19477479],
       [0.561026  ],
       [0.01261917],
       [0.60203916],
       [0.2920306 ],
       [0.48187512],
       [0.43684188],
       [0.10891308],
       [0.96443313],
       [0.24050488],
       [0.028

In [10]:
model_1.evaluate(X_test , y_test)

2/2 [==============================] - 0s 17ms/step - loss: 2.4742 - accuracy: 0.3115


[2.474158525466919, 0.31147539615631104]

In [11]:
# I should round my probabilities because i will say that if my prediction probabilities is less than 0.5 , this will be 0 label.
tf.squeeze(tf.round(model_1_preds)).dtype

tf.float32

In [12]:
new_pred = tf.cast(tf.squeeze(tf.round(model_1_preds)), tf.int64)
new_pred

<tf.Tensor: shape=(61,), dtype=int64, numpy=
array([1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1])>

In [13]:
y_test.shape

(61,)

In [14]:
X_test.shape , y_test.shape

((61, 13), (61,))

In [15]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Assuming 'y_true' contains the true labels and 'y_pred' contains the predicted labels
accuracy = accuracy_score(y_test, new_pred)
precision = precision_score(y_test, new_pred)
recall = recall_score(y_test, new_pred)
f1 = f1_score(y_test, new_pred)
conf_matrix = confusion_matrix(y_test, new_pred)

print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")
print(f"Confusion Matrix:\n{conf_matrix}")

Accuracy: 0.3114754098360656
Precision: 0.375
Recall: 0.46875
F1 Score: 0.4166666666666667
Confusion Matrix:
[[ 4 25]
 [17 15]]


In [16]:
from sklearn.metrics import classification_report
print(classification_report( y_test , new_pred )  )

              precision    recall  f1-score   support

           0       0.19      0.14      0.16        29
           1       0.38      0.47      0.42        32

    accuracy                           0.31        61
   macro avg       0.28      0.30      0.29        61
weighted avg       0.29      0.31      0.29        61



# THESE WERE GENERAL VISION , NOW I WILL DIVE INTO

In [17]:
## Standart imports
import numpy as np
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt


## Getting data ready to be used in neural network
1. Split the data into features and labels ( X & y).
2. Filling ( also called imputing ) missing values.
3. Converting non-numerical values to numerical values ( also called feature encoding )

In [18]:
heart_disease = pd.read_csv("/content/heart-disease.csv")
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

### 1. Split data into features and labels ( X & y )

In [19]:
X = heart_disease.drop("target" , axis = 1)
y = heart_disease["target"]
X

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0     2  
3        2   0     2  
4        2   0     2  
..     ...  ..   ...  
298      1   0     3  
299      1   0     3  
300      1   2     3  
301      1   1     3  
302      1   1     2  

[303 rows x 13 columns]

In [20]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

### Split the data into training and test set

In [21]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(
    X , y , test_size = 0.2 , random_state = 42
)
len(X_train) , len(X_test) , len(y_train) , len(y_test)

(242, 61, 242, 61)

### Make sure our data is all numerical

# We will use car_sales_extended data because our heart disease data is fully numerical

In [22]:
!wget https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/car-sales-extended.csv

--2023-09-13 14:10:13--  https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/car-sales-extended.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 26277 (26K) [text/plain]
Saving to: ‘car-sales-extended.csv.1’

car-sales-extended. 100%[===================>]  25.66K  --.-KB/s    in 0s      

2023-09-13 14:10:14 (85.0 MB/s) - ‘car-sales-extended.csv.1’ saved [26277/26277]



In [23]:
car_sales_extended = pd.read_csv("/content/car-sales-extended.csv")
car_sales_extended

Make Colour  Odometer (KM)  Doors  Price
0     Honda  White          35431      4  15323
1       BMW   Blue         192714      5  19943
2     Honda  White          84714      4  28343
3    Toyota  White         154365      4  13434
4    Nissan   Blue         181577      3  14043
..      ...    ...            ...    ...    ...
995  Toyota  Black          35820      4  32042
996  Nissan  White         155144      3   5716
997  Nissan   Blue          66604      4  31570
998   Honda  White         215883      4   4001
999  Toyota   Blue         248360      4  12732

[1000 rows x 5 columns]

In [24]:
car_sales_extended.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Make           1000 non-null   object
 1   Colour         1000 non-null   object
 2   Odometer (KM)  1000 non-null   int64 
 3   Doors          1000 non-null   int64 
 4   Price          1000 non-null   int64 
dtypes: int64(3), object(2)
memory usage: 39.2+ KB


In [25]:
car_sales_extended["Doors"].value_counts()  # 3 farklı şey oldugu icin categorical olarak alabiliriz yani one hot encoder yapıcaz.

4    856
5     79
3     65
Name: Doors, dtype: int64

In [26]:
# Split into car_sales data features and labels
X_car = car_sales_extended.drop("Price" , axis = 1)
y_car = car_sales_extended["Price"]

# Split into training and test set
X_train_car , X_test_car , y_train_car , y_test_car = train_test_split(
    X_car , y_car , test_size = 0.2
)
len(X_train_car) , len(X_test_car) , len(y_train_car) , len(y_test_car)


(800, 200, 800, 200)

## One hot encoding for our string variables

### ColumnTransformer kullanmamızın sebebi remainder = "passthrough" ile OneHotEncoder yapmayacağımız columnları hiçbir şey yapmadan korumak istediğimiz için. ColumnTransformer bize OneHotEncode gibi bazı şeyleri transform edip transform etmek istemediğimiz columnları da korumamızı sağlıyor.

### Mesela arabamız red
Toyota   Green Red Blue
                 
                         0      1       0         

In [27]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
categorical_features = [ "Make" , "Colour" , "Doors" ]
one_hot = OneHotEncoder()
# ColumnTransformer gonna accept a list of tuples with a name , in this case we will call it one_hot and then we will pass the actual transformer that we want to use and we are going to pass it the list of features we would like to transform
transformer = ColumnTransformer( [ (
    "one_hot" ,  # Just name
    one_hot ,  # Our transformer
    categorical_features  # Our columns which we want to transform
 ) ]  , remainder = "passthrough"
)
transformed_X = transformer.fit_transform(X_car)
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [28]:
pd.DataFrame(transformed_X)  # Odometer columns is 12. column

0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

### Another way is pandas get_dummies

In [29]:
dummies = pd.get_dummies(
    car_sales_extended[ [ "Make" , "Colour" , "Doors" ] ]
)
dummies

Doors  Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  Colour_Black  \
0        4         0           1            0            0             0   
1        5         1           0            0            0             0   
2        4         0           1            0            0             0   
3        4         0           0            0            1             0   
4        3         0           0            1            0             0   
..     ...       ...         ...          ...          ...           ...   
995      4         0           0            0            1             1   
996      3         0           0            1            0             0   
997      4         0           0            1            0             0   
998      4         0           1            0            0             0   
999      4         0           0            0            1             0   

     Colour_Blue  Colour_Green  Colour_Red  Colour_White  
0              0             0           0             1  
1              1             0           0             0  
2              0             0           0             1  
3              0             0           0             1  
4              1             0           0             0  
..           ...           ...         ...           ...  
995            0             0           0             0  
996            0             0           0             1  
997            1             0           0             0  
998            0             0           0             1  
999            1             0           0             0  

[1000 rows x 10 columns]

### Turn into training and test set with our one hot encoded data

In [30]:
X_train_car , X_test_car , y_train_car , y_test_car = train_test_split(
    transformed_X ,
    y_car ,
    test_size = 0.2 ,
    random_state = 42
)
len(X_train_car) , len(X_test_car) , len(y_train_car) , len(y_test_car)

(800, 200, 800, 200)

In [31]:
pd.DataFrame(X_train_car )

0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  112004.0
1    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35673.0
2    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  146824.0
3    0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   45152.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   69954.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
795  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  218803.0
796  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  223685.0
797  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   61876.0
798  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   28625.0
799  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  150582.0

[800 rows x 13 columns]

## Create a model. First we will start with baseline

### Because we want to predict a number , this is regression problem.

#### We cannot calculate accuracy for a regression model.

The skill or performance of a regression model must be reported as an error in those predictions.

This makes sense if you think about it. If you are predicting a numeric value like a height or a dollar amount, you don’t want to know if the model predicted the value exactly (this might be intractably difficult in practice); instead, we want to know how close the predictions were to the expected values

In [32]:
# Create a baseline
baseline = tf.keras.Sequential(
    [
        tf.keras.layers.Dense(1)
    ]
)
baseline.compile(
    loss = tf.keras.losses.mae,
    optimizer = tf.keras.optimizers.Adam() ,
    metrics = ["mae"]
)
hist = baseline.fit(
    X_train_car ,
    y_train_car ,
    epochs = 10
)

Epoch 1/10
25/25 [==============================] - 1s 4ms/step - loss: 10276.4219 - mae: 10276.4219
Epoch 2/10
25/25 [==============================] - 0s 3ms/step - loss: 10067.7686 - mae: 10067.7686
Epoch 3/10
25/25 [==============================] - 0s 2ms/step - loss: 10083.2979 - mae: 10083.2979
Epoch 4/10
25/25 [==============================] - 0s 2ms/step - loss: 10076.0986 - mae: 10076.0986
Epoch 5/10
25/25 [==============================] - 0s 3ms/step - loss: 10075.7510 - mae: 10075.7510
Epoch 6/10
25/25 [==============================] - 0s 2ms/step - loss: 10071.1309 - mae: 10071.1309
Epoch 7/10
25/25 [==============================] - 0s 3ms/step - loss: 10073.1191 - mae: 10073.1191
Epoch 8/10
25/25 [==============================] - 0s 3ms/step - loss: 10074.5898 - mae: 10074.5898
Epoch 9/10
25/25 [==============================] - 0s 5ms/step - loss: 10071.4531 - mae: 10071.4531
Epoch 10/10
25/25 [==============================] - 0s 3ms/step - loss: 10073.8008 - mae: 

In [33]:
## Evaluate on the test set
baseline.evaluate(X_test_car , y_test_car)

7/7 [==============================] - 0s 6ms/step - loss: 10442.5098 - mae: 10442.5098


[10442.509765625, 10442.509765625]

# Now we will see how we can deal with the missing values
1. Fill them with some values ( also known as imputation.)
2. Remove the samples with missing data altogether.

pandas have isna() function for missing values.

In [34]:
!wget https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/car-sales-extended-missing-data.csv

--2023-09-13 14:29:32--  https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/car-sales-extended-missing-data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 30921 (30K) [text/plain]
Saving to: ‘car-sales-extended-missing-data.csv’

car-sales-extended- 100%[===================>]  30.20K  --.-KB/s    in 0s      

2023-09-13 14:29:32 (120 MB/s) - ‘car-sales-extended-missing-data.csv’ saved [30921/30921]



In [35]:
# Importing our missing data
car_sales_missing = pd.read_csv("/content/car-sales-extended-missing-data.csv")
car_sales_missing

Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [38]:
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

## First we will create our features and labels

In [39]:
X_miss = car_sales_missing.drop("Price" , axis = 1)
y_miss = car_sales_missing["Price"]
X_miss

Make Colour  Odometer (KM)  Doors
0     Honda  White        35431.0    4.0
1       BMW   Blue       192714.0    5.0
2     Honda  White        84714.0    4.0
3    Toyota  White       154365.0    4.0
4    Nissan   Blue       181577.0    3.0
..      ...    ...            ...    ...
995  Toyota  Black        35820.0    4.0
996     NaN  White       155144.0    3.0
997  Nissan   Blue        66604.0    4.0
998   Honda  White       215883.0    4.0
999  Toyota   Blue       248360.0    4.0

[1000 rows x 4 columns]

## Second we will convert our string data to number

In [41]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
cat_var = [ "Make" , "Colour" , "Doors" ]
hot = OneHotEncoder()
ct = ColumnTransformer( [ (
    "hot" ,
     hot ,
     cat_var
 ) ] , remainder = "passthrough"
)
transformed_X_miss = ct.fit_transform(X_miss)
transformed_X_miss

<1000x16 sparse matrix of type '<class 'numpy.float64'>'
	with 4000 stored elements in Compressed Sparse Row format>