<a href="https://colab.research.google.com/github/MelihKlc/Deep-Learning/blob/main/Project_1_Heart_Disease.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# An end-to-end Scikit-Learn worfklow
1. Getting the data ready
2. Choosing the right maching learning estimator/aglorithm/model for your problem
3. Fitting your chosen machine learning model to data and using it to make a prediction
4. Evaluting a machine learning model
5. Improving predictions through experimentation (hyperparameter tuning)
6. Saving and loading a pretrained model
7. Putting it all together in a pipeline

## 1- Getting the data ready

In [1]:
!wget https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/heart-disease.csv

--2023-09-13 15:42:46--  https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/heart-disease.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11328 (11K) [text/plain]
Saving to: ‘heart-disease.csv.4’

heart-disease.csv.4 100%[===================>]  11.06K  --.-KB/s    in 0s      

2023-09-13 15:42:46 (57.2 MB/s) - ‘heart-disease.csv.4’ saved [11328/11328]



In [2]:
import pandas as pd
heart_diseas = pd.read_csv("/content/heart-disease.csv")
heart_diseas


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [3]:
# Create X (features matrix)
X = heart_diseas.drop("target" , axis = 1)
# Create y (labels)
y = heart_diseas["target"]

In [4]:
# Create test and training set
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(
    X , y , test_size = 0.2 , random_state= 42
)
len(X_train) , len(X_test) , len(y_train) , len(y_test)

(242, 61, 242, 61)

In [5]:
# Testing our output is binary or not
y.nunique() # We have zero and 1 for output

2

## Our problem is classification problem

Lets create a neural network (baseline)

In [6]:
import tensorflow as tf
baseline = tf.keras.Sequential(
    [
        tf.keras.layers.Dense(1)
    ]
)
baseline.compile(
    loss = tf.keras.losses.BinaryCrossentropy() ,
    optimizer = tf.keras.optimizers.Adam() ,
    metrics = ["accuracy"]
)
hist_0 = baseline.fit(
    X_train ,
    y_train ,
    epochs = 10 ,
    validation_data = ( X_test  , y_test)
)


Epoch 1/10
8/8 [==============================] - 1s 69ms/step - loss: 8.4773 - accuracy: 0.4504 - val_loss: 8.0918 - val_accuracy: 0.4754
Epoch 2/10
8/8 [==============================] - 0s 11ms/step - loss: 8.4773 - accuracy: 0.4504 - val_loss: 8.0918 - val_accuracy: 0.4754
Epoch 3/10
8/8 [==============================] - 0s 28ms/step - loss: 8.4773 - accuracy: 0.4504 - val_loss: 8.0918 - val_accuracy: 0.4754
Epoch 4/10
8/8 [==============================] - 0s 12ms/step - loss: 8.4773 - accuracy: 0.4504 - val_loss: 8.0918 - val_accuracy: 0.4754
Epoch 5/10
8/8 [==============================] - 0s 12ms/step - loss: 8.4773 - accuracy: 0.4504 - val_loss: 8.0918 - val_accuracy: 0.4754
Epoch 6/10
8/8 [==============================] - 0s 11ms/step - loss: 8.4773 - accuracy: 0.4504 - val_loss: 8.0918 - val_accuracy: 0.4754
Epoch 7/10
8/8 [==============================] - 0s 14ms/step - loss: 8.4773 - accuracy: 0.4504 - val_loss: 8.0918 - val_accuracy: 0.4754
Epoch 8/10
8/8 [===========

In [7]:
# Make prediction with our baseline
baseline_pred = baseline.predict(
    X_test
)
baseline_pred

2/2 [==============================] - 0s 5ms/step


array([[-279.5116 ],
       [-316.3934 ],
       [-219.11674],
       [-383.22757],
       [-289.8235 ],
       [-247.8478 ],
       [-273.23828],
       [-300.06967],
       [-285.92856],
       [-297.81238],
       [-246.27608],
       [-299.05304],
       [-340.93826],
       [-199.60878],
       [-259.32343],
       [-285.2485 ],
       [-268.383  ],
       [-220.14952],
       [-298.13892],
       [-220.16457],
       [-278.581  ],
       [-276.6578 ],
       [-235.47044],
       [-332.49744],
       [-269.51584],
       [-274.2123 ],
       [-287.9232 ],
       [-308.27264],
       [-293.9887 ],
       [-286.10684],
       [-268.61636],
       [-252.57736],
       [-266.8987 ],
       [-249.12135],
       [-255.11653],
       [-287.75665],
       [-288.21466],
       [-296.09692],
       [-258.97784],
       [-302.64816],
       [-274.64212],
       [-275.04318],
       [-255.03227],
       [-263.55054],
       [-296.6584 ],
       [-267.84244],
       [-256.09634],
       [-272.

In [8]:
# Improving our model because now it seem like sh1t. I will add activations and output layer
model_1 = tf.keras.Sequential(
    [
        tf.keras.layers.Dense(10 , activation = "relu") ,
        tf.keras.layers.Dense(1 , activation = "sigmoid")
    ]
)
model_1.compile(
    loss = tf.keras.losses.BinaryCrossentropy() ,
    optimizer = tf.keras.optimizers.Adam() ,
    metrics = ["accuracy"]
)
hist_1 = model_1.fit(
    X_train ,
    y_train ,
    epochs = 10 ,
    validation_data = ( X_test  , y_test)
)


Epoch 1/10
8/8 [==============================] - 2s 77ms/step - loss: 71.5992 - accuracy: 0.4504 - val_loss: 62.6474 - val_accuracy: 0.4754
Epoch 2/10
8/8 [==============================] - 0s 14ms/step - loss: 62.9148 - accuracy: 0.4504 - val_loss: 54.6028 - val_accuracy: 0.4754
Epoch 3/10
8/8 [==============================] - 0s 13ms/step - loss: 54.1340 - accuracy: 0.4504 - val_loss: 46.0833 - val_accuracy: 0.4754
Epoch 4/10
8/8 [==============================] - 0s 20ms/step - loss: 44.9088 - accuracy: 0.4504 - val_loss: 37.2689 - val_accuracy: 0.4754
Epoch 5/10
8/8 [==============================] - 0s 19ms/step - loss: 35.6191 - accuracy: 0.4504 - val_loss: 28.1616 - val_accuracy: 0.4754
Epoch 6/10
8/8 [==============================] - 0s 33ms/step - loss: 25.6200 - accuracy: 0.4504 - val_loss: 19.2523 - val_accuracy: 0.4590
Epoch 7/10
8/8 [==============================] - 0s 19ms/step - loss: 16.4622 - accuracy: 0.4339 - val_loss: 11.3704 - val_accuracy: 0.3934
Epoch 8/10
8/

In [9]:
model_1_preds = model_1.predict(X_test)
model_1_preds

2/2 [==============================] - 0s 11ms/step


array([[1.0000000e+00],
       [1.0000000e+00],
       [8.5826862e-01],
       [9.9999982e-01],
       [9.9999589e-01],
       [9.5679408e-01],
       [9.9946415e-01],
       [1.0000000e+00],
       [1.0000000e+00],
       [9.9806398e-01],
       [9.9996495e-01],
       [1.0000000e+00],
       [1.6095312e-01],
       [9.9988139e-01],
       [4.8077095e-06],
       [3.1163866e-02],
       [1.8850400e-08],
       [9.9999994e-01],
       [1.0000000e+00],
       [1.0000000e+00],
       [1.0000000e+00],
       [1.0000000e+00],
       [1.0000000e+00],
       [1.0000000e+00],
       [8.5443449e-01],
       [2.8003764e-01],
       [1.0000000e+00],
       [5.5216651e-02],
       [1.0000000e+00],
       [2.9967871e-02],
       [1.0000000e+00],
       [9.9999988e-01],
       [1.0000000e+00],
       [5.4922462e-02],
       [1.0000000e+00],
       [9.9998271e-01],
       [3.5382581e-01],
       [8.4060431e-03],
       [2.1852402e-02],
       [4.4056146e-06],
       [8.6978847e-01],
       [9.975675

In [10]:
model_1.evaluate(X_test , y_test)

2/2 [==============================] - 0s 28ms/step - loss: 10.2361 - accuracy: 0.2787


[10.236061096191406, 0.2786885201931]

In [11]:
# I should round my probabilities because i will say that if my prediction probabilities is less than 0.5 , this will be 0 label.
tf.squeeze(tf.round(model_1_preds)).dtype

tf.float32

In [12]:
new_pred = tf.cast(tf.squeeze(tf.round(model_1_preds)), tf.int64)
new_pred

<tf.Tensor: shape=(61,), dtype=int64, numpy=
array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1])>

In [13]:
y_test.shape

(61,)

In [14]:
X_test.shape , y_test.shape

((61, 13), (61,))

In [15]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Assuming 'y_true' contains the true labels and 'y_pred' contains the predicted labels
accuracy = accuracy_score(y_test, new_pred)
precision = precision_score(y_test, new_pred)
recall = recall_score(y_test, new_pred)
f1 = f1_score(y_test, new_pred)
conf_matrix = confusion_matrix(y_test, new_pred)

print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")
print(f"Confusion Matrix:\n{conf_matrix}")

Accuracy: 0.2786885245901639
Precision: 0.36363636363636365
Recall: 0.5
F1 Score: 0.4210526315789474
Confusion Matrix:
[[ 1 28]
 [16 16]]


In [16]:
from sklearn.metrics import classification_report
print(classification_report( y_test , new_pred )  )

              precision    recall  f1-score   support

           0       0.06      0.03      0.04        29
           1       0.36      0.50      0.42        32

    accuracy                           0.28        61
   macro avg       0.21      0.27      0.23        61
weighted avg       0.22      0.28      0.24        61



# THESE WERE GENERAL VISION , NOW I WILL DIVE INTO

In [17]:
## Standart imports
import numpy as np
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt


## Getting data ready to be used in neural network
1. Split the data into features and labels ( X & y).
2. Filling ( also called imputing ) missing values.
3. Converting non-numerical values to numerical values ( also called feature encoding )

In [18]:
heart_disease = pd.read_csv("/content/heart-disease.csv")
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

### 1. Split data into features and labels ( X & y )

In [19]:
X = heart_disease.drop("target" , axis = 1)
y = heart_disease["target"]
X

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0     2  
3        2   0     2  
4        2   0     2  
..     ...  ..   ...  
298      1   0     3  
299      1   0     3  
300      1   2     3  
301      1   1     3  
302      1   1     2  

[303 rows x 13 columns]

In [20]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

### Split the data into training and test set

In [21]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(
    X , y , test_size = 0.2 , random_state = 42
)
len(X_train) , len(X_test) , len(y_train) , len(y_test)

(242, 61, 242, 61)

### Make sure our data is all numerical

# We will use car_sales_extended data because our heart disease data is fully numerical

In [22]:
!wget https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/car-sales-extended.csv

--2023-09-13 15:43:00--  https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/car-sales-extended.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 26277 (26K) [text/plain]
Saving to: ‘car-sales-extended.csv.3’

car-sales-extended. 100%[===================>]  25.66K  --.-KB/s    in 0s      

2023-09-13 15:43:00 (89.1 MB/s) - ‘car-sales-extended.csv.3’ saved [26277/26277]



In [23]:
car_sales_extended = pd.read_csv("/content/car-sales-extended.csv")
car_sales_extended

Make Colour  Odometer (KM)  Doors  Price
0     Honda  White          35431      4  15323
1       BMW   Blue         192714      5  19943
2     Honda  White          84714      4  28343
3    Toyota  White         154365      4  13434
4    Nissan   Blue         181577      3  14043
..      ...    ...            ...    ...    ...
995  Toyota  Black          35820      4  32042
996  Nissan  White         155144      3   5716
997  Nissan   Blue          66604      4  31570
998   Honda  White         215883      4   4001
999  Toyota   Blue         248360      4  12732

[1000 rows x 5 columns]

In [24]:
car_sales_extended.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Make           1000 non-null   object
 1   Colour         1000 non-null   object
 2   Odometer (KM)  1000 non-null   int64 
 3   Doors          1000 non-null   int64 
 4   Price          1000 non-null   int64 
dtypes: int64(3), object(2)
memory usage: 39.2+ KB


In [25]:
car_sales_extended["Doors"].value_counts()  # 3 farklı şey oldugu icin categorical olarak alabiliriz yani one hot encoder yapıcaz.

4    856
5     79
3     65
Name: Doors, dtype: int64

In [26]:
# Split into car_sales data features and labels
X_car = car_sales_extended.drop("Price" , axis = 1)
y_car = car_sales_extended["Price"]

# Split into training and test set
X_train_car , X_test_car , y_train_car , y_test_car = train_test_split(
    X_car , y_car , test_size = 0.2
)
len(X_train_car) , len(X_test_car) , len(y_train_car) , len(y_test_car)


(800, 200, 800, 200)

## One hot encoding for our string variables

### ColumnTransformer kullanmamızın sebebi remainder = "passthrough" ile OneHotEncoder yapmayacağımız columnları hiçbir şey yapmadan korumak istediğimiz için. ColumnTransformer bize OneHotEncode gibi bazı şeyleri transform edip transform etmek istemediğimiz columnları da korumamızı sağlıyor.

### Mesela arabamız red
Toyota   Green Red Blue
                 
                         0      1       0         

In [27]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
categorical_features = [ "Make" , "Colour" , "Doors" ]
one_hot = OneHotEncoder()
# ColumnTransformer gonna accept a list of tuples with a name , in this case we will call it one_hot and then we will pass the actual transformer that we want to use and we are going to pass it the list of features we would like to transform
transformer = ColumnTransformer( [ (
    "one_hot" ,  # Just name
    one_hot ,  # Our transformer
    categorical_features  # Our columns which we want to transform
 ) ]  , remainder = "passthrough"
)
transformed_X = transformer.fit_transform(X_car)
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [28]:
pd.DataFrame(transformed_X)  # Odometer columns is 12. column

0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

### Another way is pandas get_dummies

In [29]:
dummies = pd.get_dummies(
    car_sales_extended[ [ "Make" , "Colour" , "Doors" ] ]
)
dummies

Doors  Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  Colour_Black  \
0        4         0           1            0            0             0   
1        5         1           0            0            0             0   
2        4         0           1            0            0             0   
3        4         0           0            0            1             0   
4        3         0           0            1            0             0   
..     ...       ...         ...          ...          ...           ...   
995      4         0           0            0            1             1   
996      3         0           0            1            0             0   
997      4         0           0            1            0             0   
998      4         0           1            0            0             0   
999      4         0           0            0            1             0   

     Colour_Blue  Colour_Green  Colour_Red  Colour_White  
0              0             0           0             1  
1              1             0           0             0  
2              0             0           0             1  
3              0             0           0             1  
4              1             0           0             0  
..           ...           ...         ...           ...  
995            0             0           0             0  
996            0             0           0             1  
997            1             0           0             0  
998            0             0           0             1  
999            1             0           0             0  

[1000 rows x 10 columns]

### Turn into training and test set with our one hot encoded data

In [30]:
X_train_car , X_test_car , y_train_car , y_test_car = train_test_split(
    transformed_X ,
    y_car ,
    test_size = 0.2 ,
    random_state = 42
)
len(X_train_car) , len(X_test_car) , len(y_train_car) , len(y_test_car)

(800, 200, 800, 200)

In [31]:
pd.DataFrame(X_train_car )

0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  112004.0
1    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35673.0
2    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  146824.0
3    0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   45152.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   69954.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
795  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  218803.0
796  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  223685.0
797  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   61876.0
798  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   28625.0
799  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  150582.0

[800 rows x 13 columns]

## Create a model. First we will start with baseline

### Because we want to predict a number , this is regression problem.

#### We cannot calculate accuracy for a regression model.

The skill or performance of a regression model must be reported as an error in those predictions.

This makes sense if you think about it. If you are predicting a numeric value like a height or a dollar amount, you don’t want to know if the model predicted the value exactly (this might be intractably difficult in practice); instead, we want to know how close the predictions were to the expected values

In [32]:
# Create a baseline
baseline = tf.keras.Sequential(
    [
        tf.keras.layers.Dense(1)
    ]
)
baseline.compile(
    loss = tf.keras.losses.mae,
    optimizer = tf.keras.optimizers.Adam() ,
    metrics = ["mae"]
)
hist = baseline.fit(
    X_train_car ,
    y_train_car ,
    epochs = 10
)

Epoch 1/10
25/25 [==============================] - 1s 3ms/step - loss: 58098.6445 - mae: 58098.6445
Epoch 2/10
25/25 [==============================] - 0s 2ms/step - loss: 55031.1602 - mae: 55031.1602
Epoch 3/10
25/25 [==============================] - 0s 2ms/step - loss: 51939.6445 - mae: 51939.6445
Epoch 4/10
25/25 [==============================] - 0s 2ms/step - loss: 48929.8867 - mae: 48929.8867
Epoch 5/10
25/25 [==============================] - 0s 3ms/step - loss: 45904.0898 - mae: 45904.0898
Epoch 6/10
25/25 [==============================] - 0s 2ms/step - loss: 42948.4258 - mae: 42948.4258
Epoch 7/10
25/25 [==============================] - 0s 2ms/step - loss: 40013.2148 - mae: 40013.2148
Epoch 8/10
25/25 [==============================] - 0s 4ms/step - loss: 37174.7852 - mae: 37174.7852
Epoch 9/10
25/25 [==============================] - 0s 3ms/step - loss: 34411.3086 - mae: 34411.3086
Epoch 10/10
25/25 [==============================] - 0s 3ms/step - loss: 31725.3867 - mae: 

In [33]:
## Evaluate on the test set
baseline.evaluate(X_test_car , y_test_car)

7/7 [==============================] - 0s 3ms/step - loss: 32440.4102 - mae: 32440.4102


[32440.41015625, 32440.41015625]

# Now we will see how we can deal with the missing values
1. Fill them with some values ( also known as imputation.)
2. Remove the samples with missing data altogether.

pandas have isna() function for missing values.

## The main takeaways:

1. Split your data first (into train/test), always keep your training & test data separate

2. Fill/transform the training set and test sets separately (this goes for filling data with pandas as well)

3. Don't use data from the future (test set) to fill data from the past (training set)

In [34]:
!wget https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/car-sales-extended-missing-data.csv

--2023-09-13 15:43:03--  https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/car-sales-extended-missing-data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 30921 (30K) [text/plain]
Saving to: ‘car-sales-extended-missing-data.csv.2’

car-sales-extended- 100%[===================>]  30.20K  --.-KB/s    in 0s      

2023-09-13 15:43:03 (79.8 MB/s) - ‘car-sales-extended-missing-data.csv.2’ saved [30921/30921]



In [35]:
# Importing our missing data
car_sales_missing = pd.read_csv("/content/car-sales-extended-missing-data.csv")
car_sales_missing

Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [36]:
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

## First , we will fill the missing values.

### Option 1 : Fill missing data with pandas

In [37]:
# Fill the "Make" column. We cannot take a mean of string values or something like this , so we will fill with "missing"
car_sales_missing["Make"].fillna("missing" , inplace = True)


# Fill the "Colour" column. Same thing with above
car_sales_missing["Colour"].fillna("missing" , inplace = True)


# Fill the "Odometer (KM)" column. We will fill with the mean of Odometer column.
car_sales_missing["Odometer (KM)"].fillna( car_sales_missing["Odometer (KM)"].mean() , inplace = True )

# Fill the "Doors" column. We will fill with the mean of Doors column.
car_sales_missing["Doors"].fillna( 4 , inplace = True )




In [38]:
car_sales_missing.isna().sum()

Make              0
Colour            0
Odometer (KM)     0
Doors             0
Price            50
dtype: int64

### Labela sahip olmayan datalarda predict çok zor olduğu için ve label columnu special bir column oldugu icin buradaki missing valueları herhangi bir şeyle doldurmayacağız. Direkt o columnları sileceğiz.

In [39]:
# Remove rows with missing Price labels
car_sales_missing.dropna(inplace=True)

In [40]:
car_sales_missing.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [41]:
len(car_sales_missing)  # Biraz data kaybı yaşıyoruz fakat bunu yapmak zorundayız.

950

## Second , we will convert our string data to number( One hot encode)

In [42]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
categorical_features = [ "Make" , "Colour" , "Doors" ]
one_hot = OneHotEncoder()
# ColumnTransformer gonna accept a list of tuples with a name , in this case we will call it one_hot and then we will pass the actual transformer that we want to use and we are going to pass it the list of features we would like to transform
transformer = ColumnTransformer( [ (
    "one_hot" ,  # Just name
    one_hot ,  # Our transformer
    categorical_features  # Our columns which we want to transform
 ) ]  , remainder = "passthrough"
)
transformed_X = transformer.fit_transform(car_sales_missing)
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        3.54310e+04, 1.53230e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        1.92714e+05, 1.99430e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        8.47140e+04, 2.83430e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        6.66040e+04, 3.15700e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.15883e+05, 4.00100e+03],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.48360e+05, 1.27320e+04]])

## Feature Scaling
### For example, say you were trying to predict the sale price of cars and the number of kilometres on their odometers varies from 6,000 to 345,000 but the median previous repair cost varies from 100 to 1,700. A machine learning algorithm may have trouble finding patterns in these wide-ranging variables.

### To fix this, there are two main types of feature scaling.

### **Normalization (also called min-max scaling)** - This rescales all the numerical values to between 0 and 1, with the lowest value being close to 0 and the highest previous value being close to 1. Scikit-Learn provides functionality for this in the

## The main takeaways: ( For scikit-learn filling values)

1. Split your data first (into train/test), always keep your training & test data separate

2. Fill/transform the training set and test sets separately (this goes for filling data with pandas as well)

3. Don't use data from the future (test set) to fill data from the past (training set)

In [43]:
## Now we will import our dataset again
car_sales_m = pd.read_csv("/content/car-sales-extended-missing-data.csv.1")
car_sales_m

Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [44]:
car_sales_m.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

### Önce labellardaki missing value olan columnları siliyoruz.

In [45]:
# Drop the rows with missing in the "Price" column
car_sales_m.dropna(subset=["Price"], inplace=True)

In [46]:
car_sales_m.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

### Second , we will split our data into features and labels then we will split into training and test set.

In [47]:
# Splitting features and labels
X_m = car_sales_m.drop("Price" , axis = 1)
y_m = car_sales_m["Price"]

# Splitting training and test set
X_train_m , X_test_m , y_train_m , y_test_m = train_test_split(
    X_m ,
    y_m ,
    test_size = 0.2 ,
    random_state = 42
)
len(X_train_m) , len(X_test_m) , len(y_train_m) , len(y_test_m)

(760, 190, 760, 190)

In [50]:
# Fill missing values with scikit-learn
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

# Fill categorical values with "missing" and fill numerical values with mean
categorical_imputer = SimpleImputer(
    strategy="constant" , fill_value = "missing"
)
# Door values 4
door_imputer = SimpleImputer(
    strategy = "constant" , fill_value = 4
)

numerical_imputer = SimpleImputer(
    strategy = "mean"
)

# Define columns
categorical_features = [ "Make" , "Colour" ]
door_features = [ "Doors" ]
numerical_features = [ "Odometer (KM)" ]

# Create an imputer (something that fills missing data)
imputer = ColumnTransformer(
    [
        ( "categorical_imputer" , categorical_imputer , categorical_features ) ,
        ( "door_imputer" , door_imputer , door_features ) ,
        ( "numerical_imputer" , numerical_imputer , numerical_features ) ,

    ] , remainder = "passthrough"
)

## We use fit_transform() on the training data and transform() on the testing data. In essence, we learn the patterns in the training set and transform it via imputation (fit, then transform). Then we take those same patterns and fill the test set (transform only).

In [51]:
# Now we will fit on X_train_m and transform X_train_m , X_test_m
imputer.fit(X_train_m)
X_train_filled = imputer.transform(X_train_m)
X_test_filled = imputer.transform(X_test_m)
X_train_filled


array([['Honda', 'White', 4.0, 71934.0],
       ['Toyota', 'Red', 4.0, 162665.0],
       ['Honda', 'White', 4.0, 42844.0],
       ...,
       ['Toyota', 'White', 4.0, 196225.0],
       ['Honda', 'Blue', 4.0, 133117.0],
       ['Honda', 'missing', 4.0, 150582.0]], dtype=object)