<a href="https://colab.research.google.com/github/MelihKlc/Deep-Learning/blob/main/Project_1_Heart_Disease.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# An end-to-end Scikit-Learn worfklow
1. Getting the data ready
2. Choosing the right maching learning estimator/aglorithm/model for your problem
3. Fitting your chosen machine learning model to data and using it to make a prediction
4. Evaluting a machine learning model
5. Improving predictions through experimentation (hyperparameter tuning)
6. Saving and loading a pretrained model
7. Putting it all together in a pipeline

## 1- Getting the data ready

In [1]:
!wget https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/heart-disease.csv

--2023-09-13 12:27:07--  https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/heart-disease.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11328 (11K) [text/plain]
Saving to: ‘heart-disease.csv.1’

heart-disease.csv.1 100%[===================>]  11.06K  --.-KB/s    in 0s      

2023-09-13 12:27:07 (84.1 MB/s) - ‘heart-disease.csv.1’ saved [11328/11328]



In [2]:
import pandas as pd
heart_diseas = pd.read_csv("/content/heart-disease.csv")
heart_diseas


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [3]:
# Create X (features matrix)
X = heart_diseas.drop("target" , axis = 1)
# Create y (labels)
y = heart_diseas["target"]

In [4]:
# Create test and training set
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(
    X , y , test_size = 0.2 , random_state= 42
)
len(X_train) , len(X_test) , len(y_train) , len(y_test)

(242, 61, 242, 61)

In [5]:
# Testing our output is binary or not
y.nunique() # We have zero and 1 for output

2

## Our problem is classification problem

Lets create a neural network (baseline)

In [6]:
import tensorflow as tf
baseline = tf.keras.Sequential(
    [
        tf.keras.layers.Dense(1)
    ]
)
baseline.compile(
    loss = tf.keras.losses.BinaryCrossentropy() ,
    optimizer = tf.keras.optimizers.Adam() ,
    metrics = ["accuracy"]
)
hist_0 = baseline.fit(
    X_train ,
    y_train ,
    epochs = 10 ,
    validation_data = ( X_test  , y_test)
)


Epoch 1/10
8/8 [==============================] - 2s 65ms/step - loss: 6.8994 - accuracy: 0.5331 - val_loss: 7.0367 - val_accuracy: 0.5246
Epoch 2/10
8/8 [==============================] - 0s 11ms/step - loss: 6.8397 - accuracy: 0.5372 - val_loss: 6.9997 - val_accuracy: 0.5410
Epoch 3/10
8/8 [==============================] - 0s 11ms/step - loss: 6.8275 - accuracy: 0.5413 - val_loss: 6.9997 - val_accuracy: 0.5410
Epoch 4/10
8/8 [==============================] - 0s 16ms/step - loss: 6.9335 - accuracy: 0.5455 - val_loss: 6.9997 - val_accuracy: 0.5410
Epoch 5/10
8/8 [==============================] - 0s 11ms/step - loss: 6.9329 - accuracy: 0.5455 - val_loss: 6.9997 - val_accuracy: 0.5410
Epoch 6/10
8/8 [==============================] - 0s 13ms/step - loss: 6.9329 - accuracy: 0.5455 - val_loss: 6.9997 - val_accuracy: 0.5410
Epoch 7/10
8/8 [==============================] - 0s 19ms/step - loss: 6.9329 - accuracy: 0.5455 - val_loss: 6.9997 - val_accuracy: 0.5410
Epoch 8/10
8/8 [===========

In [7]:
# Make prediction with our baseline
baseline_pred = baseline.predict(
    X_test
)
baseline_pred

2/2 [==============================] - 0s 10ms/step


array([[14.231169  ],
       [14.888563  ],
       [24.67031   ],
       [-0.31359315],
       [13.704838  ],
       [20.712395  ],
       [10.138844  ],
       [18.810486  ],
       [ 7.6528254 ],
       [ 7.8923965 ],
       [18.096457  ],
       [16.436407  ],
       [ 2.437061  ],
       [10.352081  ],
       [ 8.48935   ],
       [ 9.680249  ],
       [ 5.318672  ],
       [15.694691  ],
       [ 6.4385004 ],
       [20.908915  ],
       [21.342695  ],
       [ 8.9501505 ],
       [17.178528  ],
       [17.997944  ],
       [ 7.707412  ],
       [11.265513  ],
       [16.53121   ],
       [ 9.250596  ],
       [15.504616  ],
       [ 6.525274  ],
       [14.566802  ],
       [18.280848  ],
       [12.643531  ],
       [ 6.235157  ],
       [20.47299   ],
       [13.0439005 ],
       [ 7.914883  ],
       [ 8.2009945 ],
       [11.217974  ],
       [ 3.799994  ],
       [15.506851  ],
       [16.227646  ],
       [16.815     ],
       [ 8.302251  ],
       [ 4.810112  ],
       [ 9

In [8]:
# Improving our model because now it seem like sh1t. I will add activations and output layer
model_1 = tf.keras.Sequential(
    [
        tf.keras.layers.Dense(10 , activation = "relu") ,
        tf.keras.layers.Dense(1 , activation = "sigmoid")
    ]
)
model_1.compile(
    loss = tf.keras.losses.BinaryCrossentropy() ,
    optimizer = tf.keras.optimizers.Adam() ,
    metrics = ["accuracy"]
)
hist_1 = model_1.fit(
    X_train ,
    y_train ,
    epochs = 10 ,
    validation_data = ( X_test  , y_test)
)


Epoch 1/10
8/8 [==============================] - 4s 216ms/step - loss: 63.3574 - accuracy: 0.4504 - val_loss: 55.3660 - val_accuracy: 0.4754
Epoch 2/10
8/8 [==============================] - 0s 27ms/step - loss: 55.8340 - accuracy: 0.4504 - val_loss: 48.2500 - val_accuracy: 0.4754
Epoch 3/10
8/8 [==============================] - 0s 41ms/step - loss: 48.0712 - accuracy: 0.4504 - val_loss: 40.8856 - val_accuracy: 0.4754
Epoch 4/10
8/8 [==============================] - 0s 41ms/step - loss: 40.1392 - accuracy: 0.4504 - val_loss: 33.2138 - val_accuracy: 0.4754
Epoch 5/10
8/8 [==============================] - 0s 33ms/step - loss: 31.7073 - accuracy: 0.4504 - val_loss: 25.3261 - val_accuracy: 0.4754
Epoch 6/10
8/8 [==============================] - 0s 43ms/step - loss: 23.1352 - accuracy: 0.4504 - val_loss: 17.1454 - val_accuracy: 0.4754
Epoch 7/10
8/8 [==============================] - 0s 36ms/step - loss: 14.2822 - accuracy: 0.4339 - val_loss: 9.4548 - val_accuracy: 0.3770
Epoch 8/10
8/

In [9]:
model_1_preds = model_1.predict(X_test)
model_1_preds

2/2 [==============================] - 0s 38ms/step


array([[1.0000000e+00],
       [1.0000000e+00],
       [9.1566207e-08],
       [1.0000000e+00],
       [1.3236237e-02],
       [9.0958216e-05],
       [9.9999917e-01],
       [1.0000000e+00],
       [9.9999994e-01],
       [9.9990761e-01],
       [2.2157623e-01],
       [1.0000000e+00],
       [9.9999642e-01],
       [9.9566615e-01],
       [5.9273061e-03],
       [9.9982864e-01],
       [9.2078644e-01],
       [9.2072618e-01],
       [1.0000000e+00],
       [1.9184871e-02],
       [9.9918610e-01],
       [1.0000000e+00],
       [9.9927980e-01],
       [9.9993455e-01],
       [9.9998277e-01],
       [9.9995029e-01],
       [1.0000000e+00],
       [9.9866623e-01],
       [1.0000000e+00],
       [9.5282739e-01],
       [9.9996901e-01],
       [6.9520783e-01],
       [9.9999100e-01],
       [4.4689769e-01],
       [9.9945307e-01],
       [8.7275732e-01],
       [9.8344886e-01],
       [9.9921429e-01],
       [9.7268009e-01],
       [9.7834796e-01],
       [9.9439323e-01],
       [2.948395

In [13]:
model_1.evaluate(X_test , y_test)

2/2 [==============================] - 0s 11ms/step - loss: 7.3552 - accuracy: 0.4262


[7.355188369750977, 0.4262295067310333]

In [24]:
# I should round my probabilities because i will say that if my prediction probabilities is less than 0.5 , this will be 0 label.
tf.squeeze(tf.round(model_1_preds)).dtype

tf.float32

In [26]:
new_pred = tf.cast(tf.squeeze(tf.round(model_1_preds)), tf.int64)
new_pred

<tf.Tensor: shape=(61,), dtype=int64, numpy=
array([1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1])>

In [12]:
y_test.shape

(61,)

In [18]:
X_test.shape , y_test.shape

((61, 13), (61,))

In [29]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Assuming 'y_true' contains the true labels and 'y_pred' contains the predicted labels
accuracy = accuracy_score(y_test, new_pred)
precision = precision_score(y_test, new_pred)
recall = recall_score(y_test, new_pred)
f1 = f1_score(y_test, new_pred)
conf_matrix = confusion_matrix(y_test, new_pred)

print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")
print(f"Confusion Matrix:\n{conf_matrix}")

Accuracy: 0.4262295081967213
Precision: 0.46808510638297873
Recall: 0.6875
F1 Score: 0.5569620253164557
Confusion Matrix:
[[ 4 25]
 [10 22]]


In [30]:
from sklearn.metrics import classification_report
print(classification_report( y_test , new_pred )  )

              precision    recall  f1-score   support

           0       0.29      0.14      0.19        29
           1       0.47      0.69      0.56        32

    accuracy                           0.43        61
   macro avg       0.38      0.41      0.37        61
weighted avg       0.38      0.43      0.38        61



# THESE WERE GENERAL VISION , NOW I WILL DIVE INTO

In [31]:
## Standart imports
import numpy as np
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt


## Getting data ready to be used in neural network
1. Split the data into features and labels ( X & y).
2. Filling ( also called imputing ) missing values.
3. Converting non-numerical values to numerical values ( also called feature encoding )

In [34]:
heart_disease = pd.read_csv("/content/heart-disease.csv")
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

### 1. Split data into features and labels ( X & y )

In [36]:
X = heart_disease.drop("target" , axis = 1)
y = heart_disease["target"]
X

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0     2  
3        2   0     2  
4        2   0     2  
..     ...  ..   ...  
298      1   0     3  
299      1   0     3  
300      1   2     3  
301      1   1     3  
302      1   1     2  

[303 rows x 13 columns]

In [37]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

### Split the data into training and test set

In [38]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(
    X , y , test_size = 0.2 , random_state = 42
)
len(X_train) , len(X_test) , len(y_train) , len(y_test)

(242, 61, 242, 61)

### Make sure our data is all numerical

#### We will use car_sales_extended data because our heart disease data is fully numerical

In [39]:
!wget https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/car-sales-extended.csv

--2023-09-13 13:07:51--  https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/car-sales-extended.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 26277 (26K) [text/plain]
Saving to: ‘car-sales-extended.csv’

car-sales-extended. 100%[===================>]  25.66K  --.-KB/s    in 0s      

2023-09-13 13:07:51 (73.5 MB/s) - ‘car-sales-extended.csv’ saved [26277/26277]



In [40]:
car_sales_extended = pd.read_csv("/content/car-sales-extended.csv")
car_sales_extended

Make Colour  Odometer (KM)  Doors  Price
0     Honda  White          35431      4  15323
1       BMW   Blue         192714      5  19943
2     Honda  White          84714      4  28343
3    Toyota  White         154365      4  13434
4    Nissan   Blue         181577      3  14043
..      ...    ...            ...    ...    ...
995  Toyota  Black          35820      4  32042
996  Nissan  White         155144      3   5716
997  Nissan   Blue          66604      4  31570
998   Honda  White         215883      4   4001
999  Toyota   Blue         248360      4  12732

[1000 rows x 5 columns]

In [42]:
car_sales_extended.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Make           1000 non-null   object
 1   Colour         1000 non-null   object
 2   Odometer (KM)  1000 non-null   int64 
 3   Doors          1000 non-null   int64 
 4   Price          1000 non-null   int64 
dtypes: int64(3), object(2)
memory usage: 39.2+ KB


In [44]:
# Split into car_sales data features and labels
X_car = car_sales_extended.drop("Price" , axis = 1)
y_car = car_sales_extended["Price"]

# Split into training and test set
X_train_car , X_test_car , y_train_car , y_test_car = train_test_split(
    X_car , y_car , test_size = 0.2
)
len(X_train_car) , len(X_test_car) , len(y_train_car) , len(y_test_car)


(800, 200, 800, 200)

### Number predict etmek istediğimiz için regression problem

In [46]:
# Create a baseline
baseline = tf.keras.Sequential(
    [
        tf.keras.layers.Dense(1)
    ]
)
baseline.compile(
    loss = tf.keras.losses.SparseCategoricalCrossentropy() ,
    optimizer = tf.keras.optimizers.Adam() ,
    metrics = ["mae"]
)
hist = baseline.fit(
    X_train_car ,
    y_train_car ,
    epochs = 10
)

ValueError: ignored